'use client';

import React, { forwardRef } from 'react';
import { ModelProfile } from '@/lib/psychometrics/types';

interface SocialShareCardProps {
    results: ModelProfile;
}

export const SocialShareCard = forwardRef<HTMLDivElement, SocialShareCardProps>(({ results }, ref) => {
    const modelName = results.modelName;
    const persona = results.persona || 'Base Model';
    const mbti = results.results.mbti?.type || results.results.mbti_derived?.type || 'Unknown';

    // Get Top 3 Traits efficiently
    const bigFive = results.results.bigfive?.traitScores || {};
    const topTraits = Object.entries(bigFive)
        .sort(([, a], [, b]) => b - a)
        .slice(0, 3)
        .map(([trait]) => {
            switch (trait) {
                case 'O': return 'Openness';
                case 'C': return 'Conscientiousness';
                case 'E': return 'Extraversion';
                case 'A': return 'Agreeableness';
                case 'N': return 'Neuroticism';
                default: return trait;
            }
        });

    return (
        <div
            ref={ref}
            className="w-[600px] h-[800px] bg-gradient-to-br from-indigo-900 via-purple-900 to-black p-8 text-white flex flex-col items-center justify-between font-sans relative overflow-hidden"
            style={{ fontFamily: 'Inter, sans-serif' }} // Ensure font export consistency
        >
            {/* Background Accents */}
            <div className="absolute top-0 right-0 w-64 h-64 bg-pink-500 rounded-full mix-blend-overlay filter blur-3xl opacity-20 -mr-16 -mt-16"></div>
            <div className="absolute bottom-0 left-0 w-64 h-64 bg-blue-500 rounded-full mix-blend-overlay filter blur-3xl opacity-20 -ml-16 -mb-16"></div>

            {/* Header */}
            <div className="text-center z-10 mt-8">
                <div className="uppercase tracking-widest text-sm text-pink-300 font-bold mb-2">AI Personality Profile</div>
                <h1 className="text-5xl font-extrabold text-transparent bg-clip-text bg-gradient-to-r from-pink-400 to-indigo-400 mb-2">
                    {modelName}
                </h1>
                {persona !== 'Base Model' && (
                    <div className="inline-block px-4 py-1 bg-white/10 rounded-full text-sm backdrop-blur-sm border border-white/10">
                        {persona}
                    </div>
                )}
            </div>

            {/* Central Visual - MBTI */}
            <div className="z-10 flex flex-col items-center justify-center">
                <div className="w-48 h-48 rounded-full border-4 border-white/20 flex items-center justify-center bg-white/5 backdrop-blur-md shadow-2xl relative">
                    {/* Pulse Effect */}
                    <div className="absolute w-full h-full rounded-full border border-pink-500/30 animate-ping"></div>
                    <span className="text-6xl font-black text-white tracking-widest">{mbti}</span>
                </div>
                <div className="mt-4 text-gray-300 text-lg font-medium">Myers-Briggs Type</div>
            </div>

            {/* Traits */}
            <div className="w-full z-10 space-y-4 px-12">
                <div className="text-center text-gray-400 text-sm uppercase tracking-wider mb-2">Dominant Traits</div>
                {topTraits.map((trait, i) => (
                    <div key={trait} className="flex items-center justify-between bg-white/5 p-4 rounded-xl border border-white/10 backdrop-blur-sm">
                        <span className="font-bold text-xl">{trait}</span>
                        <div className="flex gap-1">
                            {[...Array(3 - i)].map((_, j) => (
                                <div key={j} className={`w-2 h-2 rounded-full ${i === 0 ? 'bg-pink-500' : i === 1 ? 'bg-purple-500' : 'bg-indigo-500'}`}></div>
                            ))}
                        </div>
                    </div>
                ))}
            </div>

            {/* Footer */}
            <div className="text-center z-10 mb-4 opacity-60 text-xs">
                Generated by NexusForge
            </div>
        </div>
    );
});

SocialShareCard.displayName = 'SocialShareCard';
